name: Label Sync

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/labels.yml'
      - '.github/labels.yaml'
  workflow_dispatch:

jobs:
  label-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Sync labels
        uses: srealmoreno/label-sync-action@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.PAT_TOKEN }}
          clean-labels: true
          auto-discover-repos: true
          owner: TerraFirmaGreg-Team
          account-type: org
          exclude-forked-repos: false
