name: Sync Labels and Projects
run-name: "ðŸ”„ Sync Labels & Projects"

on:
  project_card:
    types: [created, moved, converted, deleted]
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:


  sync-projects-to-labels:
    name: "ðŸ“‹ Projects â†’ Labels"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto card labeler
        uses: Xikaro/sync-card-labeler@v3.0.1
